version: "3"
services:
  trading-bot-binance:
    container_name: trading-bot-binance
    image: tenjnd/trading-bot:latest
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - trading-data-volume:/app/trading_data
    entrypoint: ["python"]
    command: ["src/main.py", "trade"]

  trading-bot-kucoin:
    container_name: trading-bot-kucoin
    image: tenjnd/trading-bot:latest
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - trading-data-volume:/app/trading_data
    entrypoint: ["python"]
    command: ["src/main.py", "trade", "-exch", "kucoinfutures"]

volumes:
  trading-data-volume:
