version: "3"
services:
#  trading-bot-controller:
#    container_name: trading-bot-controller
#    image: tenjnd/trading-bot:latest
#    env_file:
#      - .env
#    network_mode: "host"
#    entrypoint: ["python"]
#    command: ["src/main.py"]

  trading-bot-bybit:
    container_name: trading-bot-bybit
    image: tenjnd/trading-bot:latest
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - trading-data-volume:/app/trading_data
    entrypoint: [ "python" ]
    command: [ "src/main.py", "trade", "-exch", "bybit" ]

  trading-bot-kucoin:
    container_name: trading-bot-kucoin
    image: tenjnd/trading-bot:latest
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - trading-data-volume:/app/trading_data
    entrypoint: ["python"]
    command: ["src/main.py", "trade", "-exch", "kucoinfutures"]

volumes:
  trading-data-volume:
