"""add exchange id into orders table

Revision ID: 041ab0ceb0ac
Revises: 80e3eed18587
Create Date: 2024-09-06 13:45:05.427047

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '041ab0ceb0ac'
down_revision = '80e3eed18587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('exchange', sa.String(), nullable=False, server_default='binance'),
                  schema='turtle_strategy')
    op.alter_column('orders', 'agg_trade_id',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    schema='turtle_strategy')
    op.alter_column('orders', 'atr',
                    existing_type=sa.NUMERIC(),
                    nullable=False,
                    schema='turtle_strategy')
    op.alter_column('orders', 'position_status',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    schema='turtle_strategy')
    op.alter_column('orders', 'action',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'action',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    schema='turtle_strategy')
    op.alter_column('orders', 'position_status',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    schema='turtle_strategy')
    op.alter_column('orders', 'atr',
                    existing_type=sa.NUMERIC(),
                    nullable=True,
                    schema='turtle_strategy')
    op.alter_column('orders', 'agg_trade_id',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    schema='turtle_strategy')
    op.drop_column('orders', 'exchange', schema='turtle_strategy')
    # ### end Alembic commands ###
