"""add_period_and_timeframe

Revision ID: 1440dfcfb9b5
Revises: df1b3f7db1a5
Create Date: 2024-11-09 17:57:15.411734

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1440dfcfb9b5'
down_revision = 'df1b3f7db1a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turtle_back_test',
                  sa.Column('timeframe', sa.String(), nullable=True),
                  schema='turtle_strategy')
    op.add_column('turtle_back_test',
                  sa.Column('period_days', sa.Integer(), nullable=True),
                  schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turtle_back_test', 'period_days', schema='turtle_strategy')
    op.drop_column('turtle_back_test', 'timeframe', schema='turtle_strategy')
    # ### end Alembic commands ###
