"""ordrs candle timeframe

Revision ID: 27928ea81fdc
Revises: 7544da8bf7ca
Create Date: 2024-11-24 09:49:44.207856

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '27928ea81fdc'
down_revision = '7544da8bf7ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('candle_timeframe', sa.BigInteger(), nullable=True), schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'candle_timeframe', schema='turtle_strategy')
    # ### end Alembic commands ###
