"""change type

Revision ID: 30e7d119adc1
Revises: 93e094cfc111
Create Date: 2024-12-23 11:04:44.840461

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '30e7d119adc1'
down_revision = '93e094cfc111'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance_report', 'candle_timestamp',
                    existing_type=sa.BIGINT(),
                    type_=sa.String(),
                    existing_nullable=True,
                    schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance_report', 'candle_timestamp',
                    existing_type=sa.String(),
                    type_=sa.BIGINT(),
                    existing_nullable=True,
                    schema='turtle_strategy')
    # ### end Alembic commands ###
