"""sub_account column in strategy

Revision ID: 3f114c11d9ae
Revises: 8b3470275683
Create Date: 2024-11-17 15:41:04.099072

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3f114c11d9ae'
down_revision = '8b3470275683'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_settings', sa.Column('sub_account_id', sa.String(), nullable=True),
                  schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_settings', 'sub_account_id', schema='turtle_strategy')
    # ### end Alembic commands ###
