"""shit trader columns

Revision ID: 4605b1574dce
Revises: 1f27990760f9
Create Date: 2025-01-28 09:37:29.269205

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4605b1574dce'
down_revision = '1f27990760f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_settings', sa.Column('manual_side', sa.String(), nullable=True), schema='turtle_strategy')
    op.add_column('strategy_settings', sa.Column('manual_standby_mode', sa.Boolean(), nullable=True),
                  schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_settings', 'manual_standby_mode', schema='turtle_strategy')
    op.drop_column('strategy_settings', 'manual_side', schema='turtle_strategy')
    # ### end Alembic commands ###
