"""add agent_name to agent actions

Revision ID: 7544da8bf7ca
Revises: 3f114c11d9ae
Create Date: 2024-11-21 13:40:34.694668

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7544da8bf7ca'
down_revision = '3f114c11d9ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_actions', sa.Column('agent_name', sa.String(), nullable=True), schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_actions', 'agent_name', schema='turtle_strategy')
    # ### end Alembic commands ###
