"""add contract size and strategy activity

Revision ID: 7d6a90cec4d6
Revises: ae23af2c91a1
Create Date: 2024-09-15 15:45:30.509868

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7d6a90cec4d6'
down_revision = 'ae23af2c91a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('contract_size', sa.Float(), nullable=True), schema='turtle_strategy')
    op.add_column('strategy_settings', sa.Column('active', sa.Boolean(), nullable=True), schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_settings', 'active', schema='turtle_strategy')
    op.drop_column('orders', 'contract_size', schema='turtle_strategy')
    # ### end Alembic commands ###
