"""upgrade nullable

Revision ID: 80e3eed18587
Revises: a7a0642b2752
Create Date: 2024-09-06 13:15:06.141654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e3eed18587'
down_revision = 'a7a0642b2752'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
