"""add capital report

Revision ID: 93e094cfc111
Revises: 27928ea81fdc
Create Date: 2024-12-23 10:42:50.457419

"""
import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op

# revision identifiers, used by Alembic.
revision = '93e094cfc111'
down_revision = '27928ea81fdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_report',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('candle_timestamp', sa.BigInteger(), nullable=True),
                    sa.Column('exchange_id', sa.String(), nullable=True),
                    sa.Column('timestamp_created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
                    sa.Column('value', sa.Float(), nullable=True),
                    sa.Column('sub_account_id', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='turtle_strategy'
                    )
    op.add_column('deposits_withdrawals', sa.Column('sub_account_id', sa.String(), nullable=True),
                  schema='turtle_strategy')
    op.add_column('deposits_withdrawals', sa.Column('person_id', sa.String(), nullable=True), schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposits_withdrawals', 'person_id', schema='turtle_strategy')
    op.drop_column('deposits_withdrawals', 'sub_account_id', schema='turtle_strategy')
    op.drop_table('balance_report', schema='turtle_strategy')
    # ### end Alembic commands ###
