"""add strategy id to orders

Revision ID: a0eb15d5f053
Revises: 7d6a90cec4d6
Create Date: 2024-09-15 18:19:38.316380

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a0eb15d5f053'
down_revision = '7d6a90cec4d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('strategy_id', sa.Integer(), nullable=True), schema='turtle_strategy')
    op.create_foreign_key(None, 'orders', 'strategy_settings', ['strategy_id'], ['id'], source_schema='turtle_strategy',
                          referent_schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', schema='turtle_strategy', type_='foreignkey')
    op.drop_column('orders', 'strategy_id', schema='turtle_strategy')
    # ### end Alembic commands ###
