"""alembic init

Revision ID: a7a0642b2752
Revises: 
Create Date: 2024-09-06 13:09:31.958214

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a7a0642b2752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'id',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    schema='turtle_strategy')
    op.create_index(op.f('ix_turtle_strategy_orders_client_order_id'), 'orders', ['client_order_id'], unique=False,
                    schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turtle_strategy_orders_client_order_id'), table_name='orders', schema='turtle_strategy')
    op.alter_column('orders', 'id',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    schema='turtle_strategy')
    # ### end Alembic commands ###
