"""update settings options

Revision ID: ae23af2c91a1
Revises: c2d5be37ffc3
Create Date: 2024-09-13 14:28:30.192341

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ae23af2c91a1'
down_revision = 'c2d5be37ffc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_settings', sa.Column('stop_loss_atr_multipl', sa.Float(), nullable=True),
                  schema='turtle_strategy')
    op.add_column('strategy_settings', sa.Column('pyramid_entry_atr_multipl', sa.Float(), nullable=True),
                  schema='turtle_strategy')
    op.add_column('strategy_settings', sa.Column('aggressive_pyramid_entry_multipl', sa.Float(), nullable=True),
                  schema='turtle_strategy')
    op.add_column('strategy_settings', sa.Column('aggressive_price_atr_ratio', sa.Float(), nullable=True),
                  schema='turtle_strategy')
    op.add_column('strategy_settings', sa.Column('pyramid_entry_limit', sa.Integer(), nullable=True),
                  schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_settings', 'pyramid_entry_limit', schema='turtle_strategy')
    op.drop_column('strategy_settings', 'aggressive_price_atr_ratio', schema='turtle_strategy')
    op.drop_column('strategy_settings', 'aggressive_pyramid_entry_multipl', schema='turtle_strategy')
    op.drop_column('strategy_settings', 'pyramid_entry_atr_multipl', schema='turtle_strategy')
    op.drop_column('strategy_settings', 'stop_loss_atr_multipl', schema='turtle_strategy')
    # ### end Alembic commands ###
