"""reinforced trader profit col

Revision ID: c0a7fa68b736
Revises: 247be699c070
Create Date: 2025-01-14 14:01:45.022983

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c0a7fa68b736'
down_revision = '247be699c070'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes_training', sa.Column('profit_closed_trades', sa.Float(), nullable=True),
                  schema='turtle_strategy')
    op.drop_column('episodes_training', 'total_profit', schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes_training',
                  sa.Column('total_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                  schema='turtle_strategy')
    op.drop_column('episodes_training', 'profit_closed_trades', schema='turtle_strategy')
    # ### end Alembic commands ###
