"""deposits_and_withdrawals_table

Revision ID: cde1af8b317d
Revises: eb5333507519
Create Date: 2024-11-08 19:25:14.892643

"""
import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cde1af8b317d'
down_revision = 'eb5333507519'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposits_withdrawals',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('exchange_id', sa.String(), nullable=True),
                    sa.Column('timestamp_created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
                    sa.Column('value', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='turtle_strategy'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposits_withdrawals', schema='turtle_strategy')
    # ### end Alembic commands ###
