"""back_test_table

Revision ID: cfd2c22098b1
Revises: cde1af8b317d
Create Date: 2024-11-09 02:35:26.296832

"""
import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cfd2c22098b1'
down_revision = 'cde1af8b317d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turtle_back_test',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('exchange_id', sa.String(), nullable=True),
                    sa.Column('init_capital', sa.Float(), nullable=True),
                    sa.Column('pl', sa.Float(), nullable=True),
                    sa.Column('pl_percent', sa.Float(), nullable=True),
                    sa.Column('final_capital', sa.Float(), nullable=True),
                    sa.Column('trades', sa.ARRAY(sa.Float()), nullable=True),
                    sa.Column('timestamp_created', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='turtle_strategy'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turtle_back_test', schema='turtle_strategy')
    # ### end Alembic commands ###
