"""reinforced trader timestamp col

Revision ID: de62e9032565
Revises: c0a7fa68b736
Create Date: 2025-01-14 14:13:49.062107

"""
import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op

# revision identifiers, used by Alembic.
revision = 'de62e9032565'
down_revision = 'c0a7fa68b736'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes_training',
                  sa.Column('timestamp_created',
                            sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
                  schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes_training', 'timestamp_created', schema='turtle_strategy')
    # ### end Alembic commands ###
