"""back_test_table_adj

Revision ID: df1b3f7db1a5
Revises: cfd2c22098b1
Create Date: 2024-11-09 02:38:54.654925

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'df1b3f7db1a5'
down_revision = 'cfd2c22098b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turtle_back_test', sa.Column('ticker', sa.String(), nullable=True), schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turtle_back_test', 'ticker', schema='turtle_strategy')
    # ### end Alembic commands ###
