"""add agent_id to strategy

Revision ID: f94b4942e9cc
Revises: 7f536ecd893d
Create Date: 2024-09-24 10:56:13.788384

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f94b4942e9cc'
down_revision = '7f536ecd893d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_settings', sa.Column('agent_id', sa.String(), nullable=True), schema='turtle_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_settings', 'agent_id', schema='turtle_strategy')
    # ### end Alembic commands ###
